const { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, ModalBuilder, TextInputBuilder, TextInputStyle, ChannelSelectMenuBuilder, UserSelectMenuBuilder, ChannelType } = require('discord.js');

function isOwner(member){ return !!member && member.guild.ownerId === member.id; }
async function dbInit(q){
  await q("CREATE TABLE IF NOT EXISTS partner_requests(id BIGSERIAL PRIMARY KEY,guild_id TEXT NOT NULL,applicant_id TEXT NOT NULL,server_name TEXT NOT NULL,invite TEXT NOT NULL,contact TEXT,description TEXT,status TEXT NOT NULL DEFAULT 'PENDING',reviewer_id TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),reviewed_at TIMESTAMPTZ)");
  await q("CREATE TABLE IF NOT EXISTS partners(id BIGSERIAL PRIMARY KEY,guild_id TEXT NOT NULL,server_name TEXT NOT NULL,invite TEXT NOT NULL,contact TEXT,notes TEXT,status TEXT NOT NULL DEFAULT 'ACTIVE',created_by TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),expires_at TIMESTAMPTZ)");
}
async function ensurePanel(guild, q, force=false){
  const ch=guild.channels.cache.find(c=>c.name==='🤝・partnerships'&&c.type===ChannelType.GuildText); if(!ch) return;
  const exists=(await ch.messages.fetch({limit:30}).catch(()=>new Map())).some(m=>m.author.id===guild.client.user.id&&m.embeds[0]?.title==='🤝 Partnership Manager');
  if(exists&&!force) return;
  const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('partner_apply').setLabel('🤝 Apply for Partnership').setStyle(ButtonStyle.Primary));
  await ch.send({embeds:[new EmbedBuilder().setTitle('🤝 Partnership Manager').setDescription('Interested in partnering with this server? Click the button below and submit your server details.\n\nApplications are reviewed by the server owner.').setColor(0x5865F2)],components:[row]}).catch(()=>{});
}
function ownerPanel(){ return {embeds:[new EmbedBuilder().setTitle('👑 Goll Owner Control').setDescription('Everything here is handled by Goll inside Discord.\n\n📨 Send Message — send a message as Goll to any channel\n📩 Goll DM — DM a member as Goll\n👮 Staff Management — manage staff without manual role work\n🤝 Partners — view active partnerships\n📋 Requests — review partnership applications\n\nOnly the server owner can use this control panel.').setColor(0x5865F2)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('owner_send_message').setLabel('📨 Send Message').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('owner_dm').setLabel('📩 Goll DM').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('owner_staff').setLabel('👮 Staff Management').setStyle(ButtonStyle.Success)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('owner_partners').setLabel('🤝 Partners').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('owner_requests').setLabel('📋 Requests').setStyle(ButtonStyle.Secondary))]}; }
function messageModal(channelId){ return new ModalBuilder().setCustomId('owner_message_modal:'+channelId).setTitle('📨 Send as Goll').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('message').setLabel('Message').setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(4000))); }
function dmModal(userId){ return new ModalBuilder().setCustomId('owner_dm_modal:'+userId).setTitle('📩 DM as Goll').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('message').setLabel('Message').setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(2000))); }
function staffPicker(){ return new ActionRowBuilder().addComponents(new UserSelectMenuBuilder().setCustomId('owner_staff_user').setPlaceholder('Select a member to manage').setMinValues(1).setMaxValues(1)); }
function staffActions(userId){ return [new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('staff_role:Trial Staff:'+userId).setLabel('📝 Trial Staff').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('staff_role:Support:'+userId).setLabel('🎫 Support').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('staff_role:Moderator:'+userId).setLabel('🔨 Moderator').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('staff_role:Admin:'+userId).setLabel('🛡️ Admin').setStyle(ButtonStyle.Danger)),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('staff_remove:'+userId).setLabel('❌ Remove Staff').setStyle(ButtonStyle.Danger),new ButtonBuilder().setCustomId('staff_active:'+userId).setLabel('🟢 Set Active').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('staff_loa:'+userId).setLabel('🏖️ Set LOA').setStyle(ButtonStyle.Secondary))]; }
function requestButtons(id){ return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('partner_accept:'+id).setLabel('✅ Accept').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('partner_deny:'+id).setLabel('❌ Deny').setStyle(ButtonStyle.Danger)); }
function setup(client,q){
  client.on('interactionCreate',async i=>{ try{
    if(i.isChatInputCommand()&&i.commandName==='gollowner'){ if(!isOwner(i.member)) return i.reply({content:'❌ Only the server owner can use Goll Owner Control.',ephemeral:true}); return i.reply({...ownerPanel(),ephemeral:true}); }
    if(i.isButton()&&i.customId==='partner_apply'){ const modal=new ModalBuilder().setCustomId('partner_apply_modal').setTitle('🤝 Partnership Application').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('server').setLabel('Server name').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(100)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('invite').setLabel('Invite link').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(200)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('contact').setLabel('Contact username').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(100)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('description').setLabel('Tell us about your server').setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(1000))); return i.showModal(modal); }
    if(i.isButton()&&i.customId==='owner_dm'){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); const menu=new UserSelectMenuBuilder().setCustomId('owner_dm_user').setPlaceholder('Select a member').setMinValues(1).setMaxValues(1); return i.reply({content:'📩 Choose who should receive the DM from Goll:',components:[new ActionRowBuilder().addComponents(menu)],ephemeral:true}); }
    if(i.isButton()&&i.customId==='owner_staff'){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); return i.reply({content:'👮 Select the member you want to manage:',components:[staffPicker()],ephemeral:true}); }
    if(i.isButton()&&i.customId==='owner_send_message'){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); const menu=new ChannelSelectMenuBuilder().setCustomId('owner_message_channel').setPlaceholder('Select a channel').setChannelTypes(ChannelType.GuildText).setMinValues(1).setMaxValues(1); return i.reply({content:'📨 Choose where Goll should send the message:',components:[new ActionRowBuilder().addComponents(menu)],ephemeral:true}); }
    if(i.isButton()&&(i.customId==='owner_partners'||i.customId==='owner_requests')){
      if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true});
      if(i.customId==='owner_partners'){ const rows=(await q('SELECT id,server_name,invite,contact,status,created_at FROM partners WHERE guild_id=$1 ORDER BY created_at DESC LIMIT 20',[i.guild.id])).rows; if(!rows.length) return i.reply({content:'🤝 No partnerships yet.',ephemeral:true}); return i.reply({embeds:[new EmbedBuilder().setTitle('🤝 Active Partnerships').setDescription(rows.map(x=>'**#'+x.id+' — '+x.server_name+'**\n'+x.invite+'\nContact: '+(x.contact||'—')+'\nStatus: **'+x.status+'**').join('\n\n')).setColor(0x5865F2)],ephemeral:true}); }
      const rows=(await q("SELECT id,server_name,invite,contact,description,applicant_id,created_at FROM partner_requests WHERE guild_id=$1 AND status='PENDING' ORDER BY created_at ASC LIMIT 10",[i.guild.id])).rows; if(!rows.length) return i.reply({content:'📋 No pending partnership requests.',ephemeral:true});
      const embeds=rows.map(x=>new EmbedBuilder().setTitle('🤝 Partnership Request #'+x.id).setDescription('**Server:** '+x.server_name+'\n**Invite:** '+x.invite+'\n**Contact:** '+x.contact+'\n**Applicant:** <@'+x.applicant_id+'>\n\n'+x.description).setColor(0xF1C40F));
      return i.reply({embeds:embeds.slice(0,10),components:rows.slice(0,5).map(x=>requestButtons(x.id)),ephemeral:true});
    }
    if(i.isUserSelectMenu()&&i.customId==='owner_dm_user'){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); return i.showModal(dmModal(i.values[0])); }
    if(i.isUserSelectMenu()&&i.customId==='owner_staff_user'){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); const member=await i.guild.members.fetch(i.values[0]).catch(()=>null); if(!member) return i.reply({content:'❌ Member not found.',ephemeral:true}); const roles=member.roles.cache.filter(r=>['👑 Owner','🛡️ Admin','🔨 Moderator','🎫 Support','📝 Trial Staff'].includes(r.name)).map(r=>r.name); return i.reply({content:'👮 Managing **'+member.user.tag+'**\nCurrent staff roles: '+(roles.length?roles.join(', '):'None')+'\n\nChoose an action:',components:staffActions(member.id),ephemeral:true}); }
    if(i.isChannelSelectMenu()&&i.customId==='owner_message_channel'){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); return i.showModal(messageModal(i.values[0])); }
    if(i.isModalSubmit()&&i.customId.startsWith('owner_dm_modal:')){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); const user=await i.client.users.fetch(i.customId.split(':')[1]).catch(()=>null); if(!user) return i.reply({content:'❌ User not found.',ephemeral:true}); const message=i.fields.getTextInputValue('message'); await user.send({embeds:[new EmbedBuilder().setDescription(message).setColor(0x5865F2).setFooter({text:'Sent by Goll'})]}); return i.reply({content:'✅ Goll sent the DM to **'+user.tag+'**.',ephemeral:true}); }
    if(i.isModalSubmit()&&i.customId.startsWith('owner_message_modal:')){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); const channel=i.guild.channels.cache.get(i.customId.split(':')[1]); if(!channel||channel.type!==ChannelType.GuildText) return i.reply({content:'❌ Channel not found.',ephemeral:true}); const message=i.fields.getTextInputValue('message'); await channel.send({embeds:[new EmbedBuilder().setDescription(message).setColor(0x5865F2).setFooter({text:'Sent by Goll'})]}); return i.reply({content:'✅ Goll sent the message in '+channel+'.',ephemeral:true}); }
    if(i.isButton()&&/^staff_role:/.test(i.customId)){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); const [,roleName,userId]=i.customId.split(':'); const target=await i.guild.members.fetch(userId).catch(()=>null); if(!target) return i.reply({content:'❌ Member not found.',ephemeral:true}); if(target.id===i.guild.ownerId) return i.reply({content:'❌ The server owner cannot be managed as staff.',ephemeral:true}); const role=i.guild.roles.cache.find(r=>r.name===''+({ 'Trial Staff':'📝 Trial Staff','Support':'🎫 Support','Moderator':'🔨 Moderator','Admin':'🛡️ Admin'}[roleName]||'')); if(!role) return i.reply({content:'❌ Staff role not found. Run /setup repair.',ephemeral:true}); const bot=i.guild.members.me; if(!bot||role.position>=bot.roles.highest.position) return i.reply({content:'❌ I cannot manage that role. Move Goll above the staff roles in Server Settings → Roles.',ephemeral:true}); const managed=['🛡️ Admin','🔨 Moderator','🎫 Support','📝 Trial Staff']; for(const name of managed){const r=i.guild.roles.cache.find(x=>x.name===name); if(r&&r.id!==role.id&&r.position<bot.roles.highest.position) await target.roles.remove(r).catch(()=>{});} await target.roles.add(role).catch(()=>null); await q('INSERT INTO staff_status(guild_id,user_id,active) VALUES($1,$2,true) ON CONFLICT(guild_id,user_id) DO UPDATE SET active=true,loa_until=NULL,loa_reason=NULL,updated_at=NOW()',[i.guild.id,target.id]); const log=i.guild.channels.cache.find(c=>c.name==='⚙️・updates-logs'&&c.type===ChannelType.GuildText); if(log) await log.send({embeds:[new EmbedBuilder().setTitle('👮 Staff Role Updated').setDescription('Member: '+target+'\nNew role: **'+role.name+'**\nChanged by: '+i.user).setColor(0x57F287)]}); return i.update({content:'✅ **'+target.user.tag+'** is now **'+role.name+'**.',components:staffActions(target.id)}); }
    if(i.isButton()&&i.customId.startsWith('staff_remove:')){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); const userId=i.customId.split(':')[1]; const target=await i.guild.members.fetch(userId).catch(()=>null); if(!target) return i.reply({content:'❌ Member not found.',ephemeral:true}); if(target.id===i.guild.ownerId) return i.reply({content:'❌ The server owner cannot be removed from staff management.',ephemeral:true}); for(const name of ['🛡️ Admin','🔨 Moderator','🎫 Support','📝 Trial Staff']){const r=i.guild.roles.cache.find(x=>x.name===name); if(r&&r.position<i.guild.members.me.roles.highest.position) await target.roles.remove(r).catch(()=>{});} await q('INSERT INTO staff_status(guild_id,user_id,active) VALUES($1,$2,true) ON CONFLICT(guild_id,user_id) DO UPDATE SET active=true,loa_until=NULL,loa_reason=NULL,updated_at=NOW()',[i.guild.id,target.id]); return i.update({content:'❌ Staff roles removed from **'+target.user.tag+'**.',components:staffActions(target.id)}); }
    if(i.isButton()&&i.customId.startsWith('staff_active:')){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); const userId=i.customId.split(':')[1]; if(userId===i.guild.ownerId) return i.reply({content:'❌ The server owner cannot be changed through Staff Manager.',ephemeral:true}); await q('INSERT INTO staff_status(guild_id,user_id,active,loa_until,loa_reason) VALUES($1,$2,true,NULL,NULL) ON CONFLICT(guild_id,user_id) DO UPDATE SET active=true,loa_until=NULL,loa_reason=NULL,updated_at=NOW()',[i.guild.id,userId]); return i.update({content:'🟢 Staff member marked **ACTIVE**.',components:staffActions(userId)}); }
    if(i.isButton()&&i.customId.startsWith('staff_loa:')){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); const userId=i.customId.split(':')[1]; if(userId===i.guild.ownerId) return i.reply({content:'❌ The server owner cannot be placed on LOA.',ephemeral:true}); const modal=new ModalBuilder().setCustomId('owner_staff_loa_modal:'+userId).setTitle('🏖️ Staff LOA').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('days').setLabel('Days (1-30)').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(2)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('reason').setLabel('Reason').setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(500))); return i.showModal(modal); }
    if(i.isModalSubmit()&&i.customId.startsWith('owner_staff_loa_modal:')){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); const userId=i.customId.split(':')[1]; const days=Math.max(1,Math.min(30,parseInt(i.fields.getTextInputValue('days'),10)||1)); const reason=i.fields.getTextInputValue('reason'); const until=new Date(Date.now()+days*86400000); await q('INSERT INTO staff_status(guild_id,user_id,active,loa_until,loa_reason) VALUES($1,$2,false,$3,$4) ON CONFLICT(guild_id,user_id) DO UPDATE SET active=false,loa_until=$3,loa_reason=$4,updated_at=NOW()',[i.guild.id,userId,until,reason]); const target=await i.guild.members.fetch(userId).catch(()=>null); if(target) await target.send({embeds:[new EmbedBuilder().setTitle('🏖️ Staff LOA').setDescription('You have been placed on LOA in **'+i.guild.name+'** for **'+days+' days**.\nReason: '+reason+'\nReturn: <t:'+Math.floor(until.getTime()/1000)+':F>').setColor(0xF1C40F)]}).catch(()=>{}); const log=i.guild.channels.cache.find(c=>c.name==='🏖️・loa-logs'&&c.type===ChannelType.GuildText); if(log) await log.send({embeds:[new EmbedBuilder().setTitle('🏖️ Staff LOA Set').setDescription('Staff: '+(target||'<@'+userId+'>')+'\nDuration: **'+days+' days**\nReason: '+reason+'\nChanged by: '+i.user).setColor(0xF1C40F)]}); return i.reply({content:'🏖️ LOA set successfully.',ephemeral:true}); }
    if(i.isModalSubmit()&&i.customId==='partner_apply_modal'){ const server=i.fields.getTextInputValue('server'),invite=i.fields.getTextInputValue('invite'),contact=i.fields.getTextInputValue('contact'),description=i.fields.getTextInputValue('description'); await q('INSERT INTO partner_requests(guild_id,applicant_id,server_name,invite,contact,description) VALUES($1,$2,$3,$4,$5,$6)',[i.guild.id,i.user.id,server,invite,contact,description]); const owner=await i.guild.fetchOwner().catch(()=>null); if(owner) await owner.send({embeds:[new EmbedBuilder().setTitle('🤝 New Partnership Request').setDescription('**Server:** '+server+'\n**Invite:** '+invite+'\n**Contact:** '+contact+'\n**Applicant:** <@'+i.user.id+'>\n\n'+description).setColor(0xF1C40F)]}).catch(()=>{}); return i.reply({content:'✅ Your partnership request has been submitted. The server owner will review it.',ephemeral:true}); }
    if(i.isButton()&&/^(partner_accept|partner_deny):/.test(i.customId)){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); const [action,id]=i.customId.split(':'); const req=(await q("SELECT * FROM partner_requests WHERE id=$1 AND guild_id=$2 AND status='PENDING'",[id,i.guild.id])).rows[0]; if(!req) return i.reply({content:'❌ This request is no longer pending.',ephemeral:true}); const status=action==='partner_accept'?'ACCEPTED':'DENIED'; await q('UPDATE partner_requests SET status=$1,reviewer_id=$2,reviewed_at=NOW() WHERE id=$3',[status,i.user.id,id]); if(status==='ACCEPTED') await q('INSERT INTO partners(guild_id,server_name,invite,contact,created_by) VALUES($1,$2,$3,$4,$5)',[i.guild.id,req.server_name,req.invite,req.contact,i.user.id]); const applicant=await i.client.users.fetch(req.applicant_id).catch(()=>null); if(applicant) await applicant.send('🤝 Your partnership request for **'+i.guild.name+'** was **'+status.toLowerCase()+'**.').catch(()=>{}); return i.update({content:(status==='ACCEPTED'?'✅':'❌')+' Request #'+id+' — **'+status+'**',embeds:[],components:[]}); }
  }catch(e){ console.error('Goll owner/partner system:',e); if(!i.replied&&!i.deferred) await i.reply({content:'❌ Something went wrong. Check the bot logs.',ephemeral:true}).catch(()=>{}); }});
  client.once('ready',async()=>{ for(const guild of client.guilds.cache.values()){ const existing=await guild.commands.fetch().catch(()=>null); if(existing&&!existing.some(x=>x.name==='gollowner')) await guild.commands.create({name:'gollowner',description:'Open the private Goll Owner Control'}).catch(e=>console.error('Owner command:',e.message)); } });
}
module.exports={setup,ensurePanel,dbInit};