const { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder, ModalBuilder, TextInputBuilder, TextInputStyle, ChannelSelectMenuBuilder, ChannelType } = require('discord.js');

function isOwner(member){ return !!member && member.guild.ownerId === member.id; }
async function dbInit(q){
  await q("CREATE TABLE IF NOT EXISTS partner_requests(id BIGSERIAL PRIMARY KEY,guild_id TEXT NOT NULL,applicant_id TEXT NOT NULL,server_name TEXT NOT NULL,invite TEXT NOT NULL,contact TEXT,description TEXT,status TEXT NOT NULL DEFAULT 'PENDING',reviewer_id TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),reviewed_at TIMESTAMPTZ)");
  await q("CREATE TABLE IF NOT EXISTS partners(id BIGSERIAL PRIMARY KEY,guild_id TEXT NOT NULL,server_name TEXT NOT NULL,invite TEXT NOT NULL,contact TEXT,notes TEXT,status TEXT NOT NULL DEFAULT 'ACTIVE',created_by TEXT,created_at TIMESTAMPTZ DEFAULT NOW(),expires_at TIMESTAMPTZ)");
}
async function ensurePanel(guild, q, force=false){
  const ch=guild.channels.cache.find(c=>c.name==='🤝・partnerships'&&c.type===ChannelType.GuildText); if(!ch) return;
  const exists=(await ch.messages.fetch({limit:30}).catch(()=>new Map())).some(m=>m.author.id===guild.client.user.id&&m.embeds[0]?.title==='🤝 Partnership Manager');
  if(exists&&!force) return;
  const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('partner_apply').setLabel('🤝 Apply for Partnership').setStyle(ButtonStyle.Primary));
  await ch.send({embeds:[new EmbedBuilder().setTitle('🤝 Partnership Manager').setDescription('Interested in partnering with this server? Click the button below and submit your server details.\n\nApplications are reviewed by the server owner.').setColor(0x5865F2)],components:[row]}).catch(()=>{});
}
function ownerPanel(){ return {embeds:[new EmbedBuilder().setTitle('👑 Goll Owner Control').setDescription('Everything here is handled by Goll inside Discord.\n\n📨 Send Message — send a message as Goll to any channel\n🤝 Partners — view active partnerships\n📋 Requests — review partnership applications\n\nOnly the server owner can use this control panel.').setColor(0x5865F2)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('owner_send_message').setLabel('📨 Send Message').setStyle(ButtonStyle.Primary),new ButtonBuilder().setCustomId('owner_partners').setLabel('🤝 Partners').setStyle(ButtonStyle.Secondary),new ButtonBuilder().setCustomId('owner_requests').setLabel('📋 Requests').setStyle(ButtonStyle.Secondary))]}; }
function messageModal(channelId){ return new ModalBuilder().setCustomId('owner_message_modal:'+channelId).setTitle('📨 Send as Goll').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('message').setLabel('Message').setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(4000))); }
function requestButtons(id){ return new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('partner_accept:'+id).setLabel('✅ Accept').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('partner_deny:'+id).setLabel('❌ Deny').setStyle(ButtonStyle.Danger)); }
function setup(client,q){
  client.on('interactionCreate',async i=>{ try{
    if(i.isChatInputCommand()&&i.commandName==='gollowner'){ if(!isOwner(i.member)) return i.reply({content:'❌ Only the server owner can use Goll Owner Control.',ephemeral:true}); return i.reply({...ownerPanel(),ephemeral:true}); }
    if(i.isButton()&&i.customId==='partner_apply'){ const modal=new ModalBuilder().setCustomId('partner_apply_modal').setTitle('🤝 Partnership Application').addComponents(new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('server').setLabel('Server name').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(100)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('invite').setLabel('Invite link').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(200)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('contact').setLabel('Contact username').setStyle(TextInputStyle.Short).setRequired(true).setMaxLength(100)),new ActionRowBuilder().addComponents(new TextInputBuilder().setCustomId('description').setLabel('Tell us about your server').setStyle(TextInputStyle.Paragraph).setRequired(true).setMaxLength(1000))); return i.showModal(modal); }
    if(i.isButton()&&i.customId==='owner_send_message'){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); const menu=new ChannelSelectMenuBuilder().setCustomId('owner_message_channel').setPlaceholder('Select a channel').setChannelTypes(ChannelType.GuildText).setMinValues(1).setMaxValues(1); return i.reply({content:'📨 Choose where Goll should send the message:',components:[new ActionRowBuilder().addComponents(menu)],ephemeral:true}); }
    if(i.isButton()&&(i.customId==='owner_partners'||i.customId==='owner_requests')){
      if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true});
      if(i.customId==='owner_partners'){ const rows=(await q('SELECT id,server_name,invite,contact,status,created_at FROM partners WHERE guild_id=$1 ORDER BY created_at DESC LIMIT 20',[i.guild.id])).rows; if(!rows.length) return i.reply({content:'🤝 No partnerships yet.',ephemeral:true}); return i.reply({embeds:[new EmbedBuilder().setTitle('🤝 Active Partnerships').setDescription(rows.map(x=>'**#'+x.id+' — '+x.server_name+'**\n'+x.invite+'\nContact: '+(x.contact||'—')+'\nStatus: **'+x.status+'**').join('\n\n')).setColor(0x5865F2)],ephemeral:true}); }
      const rows=(await q("SELECT id,server_name,invite,contact,description,applicant_id,created_at FROM partner_requests WHERE guild_id=$1 AND status='PENDING' ORDER BY created_at ASC LIMIT 10",[i.guild.id])).rows; if(!rows.length) return i.reply({content:'📋 No pending partnership requests.',ephemeral:true});
      const embeds=rows.map(x=>new EmbedBuilder().setTitle('🤝 Partnership Request #'+x.id).setDescription('**Server:** '+x.server_name+'\n**Invite:** '+x.invite+'\n**Contact:** '+x.contact+'\n**Applicant:** <@'+x.applicant_id+'>\n\n'+x.description).setColor(0xF1C40F));
      return i.reply({embeds:embeds.slice(0,10),components:rows.slice(0,5).map(x=>requestButtons(x.id)),ephemeral:true});
    }
    if(i.isChannelSelectMenu()&&i.customId==='owner_message_channel'){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); return i.showModal(messageModal(i.values[0])); }
    if(i.isModalSubmit()&&i.customId.startsWith('owner_message_modal:')){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); const channel=i.guild.channels.cache.get(i.customId.split(':')[1]); if(!channel||channel.type!==ChannelType.GuildText) return i.reply({content:'❌ Channel not found.',ephemeral:true}); const message=i.fields.getTextInputValue('message'); await channel.send({embeds:[new EmbedBuilder().setDescription(message).setColor(0x5865F2).setFooter({text:'Sent by Goll'})]}); return i.reply({content:'✅ Goll sent the message in '+channel+'.',ephemeral:true}); }
    if(i.isModalSubmit()&&i.customId==='partner_apply_modal'){ const server=i.fields.getTextInputValue('server'),invite=i.fields.getTextInputValue('invite'),contact=i.fields.getTextInputValue('contact'),description=i.fields.getTextInputValue('description'); await q('INSERT INTO partner_requests(guild_id,applicant_id,server_name,invite,contact,description) VALUES($1,$2,$3,$4,$5,$6)',[i.guild.id,i.user.id,server,invite,contact,description]); const owner=await i.guild.fetchOwner().catch(()=>null); if(owner) await owner.send({embeds:[new EmbedBuilder().setTitle('🤝 New Partnership Request').setDescription('**Server:** '+server+'\n**Invite:** '+invite+'\n**Contact:** '+contact+'\n**Applicant:** <@'+i.user.id+'>\n\n'+description).setColor(0xF1C40F)]}).catch(()=>{}); return i.reply({content:'✅ Your partnership request has been submitted. The server owner will review it.',ephemeral:true}); }
    if(i.isButton()&&/^(partner_accept|partner_deny):/.test(i.customId)){ if(!isOwner(i.member)) return i.reply({content:'❌ Owner only.',ephemeral:true}); const [action,id]=i.customId.split(':'); const req=(await q("SELECT * FROM partner_requests WHERE id=$1 AND guild_id=$2 AND status='PENDING'",[id,i.guild.id])).rows[0]; if(!req) return i.reply({content:'❌ This request is no longer pending.',ephemeral:true}); const status=action==='partner_accept'?'ACCEPTED':'DENIED'; await q('UPDATE partner_requests SET status=$1,reviewer_id=$2,reviewed_at=NOW() WHERE id=$3',[status,i.user.id,id]); if(status==='ACCEPTED') await q('INSERT INTO partners(guild_id,server_name,invite,contact,created_by) VALUES($1,$2,$3,$4,$5)',[i.guild.id,req.server_name,req.invite,req.contact,i.user.id]); const applicant=await i.client.users.fetch(req.applicant_id).catch(()=>null); if(applicant) await applicant.send('🤝 Your partnership request for **'+i.guild.name+'** was **'+status.toLowerCase()+'**.').catch(()=>{}); return i.update({content:(status==='ACCEPTED'?'✅':'❌')+' Request #'+id+' — **'+status+'**',embeds:[],components:[]}); }
  }catch(e){ console.error('Goll owner/partner system:',e); if(!i.replied&&!i.deferred) await i.reply({content:'❌ Something went wrong. Check the bot logs.',ephemeral:true}).catch(()=>{}); }});
  client.once('ready',async()=>{ for(const guild of client.guilds.cache.values()) await guild.commands.create({name:'gollowner',description:'Open the private Goll Owner Control'}).catch(e=>console.error('Owner command:',e.message)); });
}
module.exports={setup,ensurePanel,dbInit};